encoding: utf-8
exclude: [vendor]
gh_pages_url_prefix: https://chengweih001.github.io/GoogleChromeSamples
gh_url_prefix: https://chengweih001.github.io/GoogleChromeSamples/blob/gh-pages
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - package.json
  - README.md
  - node_modules
  - Gemfile
  - vendor
